In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv('review1.csv')
df2 = pd.read_csv('review2.csv')
df3 = pd.read_csv('review3.csv')
df4 = pd.read_csv('review4.csv')


In [3]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)


(205052, 6)
(3150, 5)
(38886, 2)
(155544, 2)


In [4]:
df1.head()

product_name product_price Rate  \
0  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    5   
1  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    5   
2  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    3   
3  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    1   
4  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    3   

            Review                                            Summary  \
0           super!  great cooler excellent air flow and for this p...   
1          awesome              best budget 2 fit cooler nice cooling   
2             fair  the quality is good but the power of air is de...   
3  useless product                  very bad product its a only a fan   
4             fair                                      ok ok product   

  Sentiment  
0  positive  
1  positive  
2  positive  
3  negative  
4   neutral

In [5]:
df1 = df1[['Summary','Sentiment']]

In [6]:
df1['Sentiment'] = df1['Sentiment'].map({'positive':1,'neutral':2,'negative':0})

In [7]:
df1.rename(columns={'Summary':'text','Sentiment':'label'},inplace=True)

In [8]:
df2 = df2[['verified_reviews','feedback']]

In [9]:
df2.rename(columns={'verified_reviews':'text','feedback':'label'},inplace=True)

In [10]:
df1.columns

Index(['text', 'label'], dtype='object')

In [11]:
df3.rename(columns={'content':'text','sentiment_labels':'label'},inplace=True)

In [12]:
df4.rename(columns={'content':'text','sentiment_labels':'label'},inplace=True)

In [13]:
df3['label'] = df3['label'].map({'POSITIVE':1,'NEUTRAL':2,'NEGATIVE':0})
df4['label'] = df4['label'].map({'POSITIVE':1,'NEUTRAL':2,'NEGATIVE':0})

In [14]:
df = pd.concat([df1,df2,df3,df4])

In [15]:
df['label'].value_counts()

label
1    307673
2     49336
0     45623
Name: count, dtype: int64

In [16]:
df.isnull().sum()

text     19
label     0
dtype: int64

In [17]:
df.dropna(inplace=True)

In [18]:
df.duplicated().sum()

182619

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
# for i in df['text']:
#     i = i.lower()

In [21]:
df['text'] = df['text'].str.lower()

In [22]:
import string

In [23]:
punc = string.punctuation

In [24]:
def remove_punc(text):
    # for char in punc:
    #     text = text.replace(char,'')
    # return text
    return text.translate(str.maketrans('','',punc))


In [25]:
df['text'] = df['text'].apply(remove_punc)

In [26]:
df['text']

0         great cooler excellent air flow and for this p...
1                     best budget 2 fit cooler nice cooling
2         the quality is good but the power of air is de...
3                         very bad product its a only a fan
4                                             ok ok product
                                ...                        
155532              except accessories products are genuine
155533                quality pricing and delivery on point
155534    i wouldnt even give it one star but i did for ...
155538                                        nykaa is best
155540    nykaa is the best online store for the purchas...
Name: text, Length: 219994, dtype: object

In [27]:
from textblob import TextBlob

In [28]:
def spelling_check(text):
    textBlb = TextBlob(text)
    return textBlb.correct()

In [29]:
# df['text'] = df['text'].apply(spelling_check)

In [30]:
from nltk.corpus import stopwords

In [31]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [32]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    return ' '.join([word for word in text.split() if word not in stop_words])


In [33]:
df

text  label
0       great cooler excellent air flow and for this p...      1
1                   best budget 2 fit cooler nice cooling      1
2       the quality is good but the power of air is de...      1
3                       very bad product its a only a fan      0
4                                           ok ok product      2
...                                                   ...    ...
155532            except accessories products are genuine      1
155533              quality pricing and delivery on point      1
155534  i wouldnt even give it one star but i did for ...      0
155538                                      nykaa is best      1
155540  nykaa is the best online store for the purchas...      1

[219994 rows x 2 columns]

In [34]:
df['text'] = df['text'].apply(remove_stopwords)

In [35]:
df

text  label
0       great cooler excellent air flow price amazing ...      1
1                   best budget 2 fit cooler nice cooling      1
2                           quality good power air decent      1
3                                         bad product fan      0
4                                           ok ok product      2
...                                                   ...    ...
155532                except accessories products genuine      1
155533                     quality pricing delivery point      1
155534  wouldnt even give one star comment appear orde...      0
155538                                         nykaa best      1
155540  nykaa best online store purchase genuine produ...      1

[219994 rows x 2 columns]

In [36]:
import re

In [37]:
def remove_emoji(text):
    emoji_pattern = re.compile('['
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"  # chinese char
                               u"\U00002702-\U000027B0"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"  # dingbats
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [38]:
df['text'] = df['text'].apply(remove_emoji)

In [39]:
df.duplicated().sum()

29811

In [40]:
df.drop_duplicates(inplace=True)

In [41]:
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')

def lemmatize_text(text):
    lemmatizer = WordNetLemmatizer()
    lemmatized_text = []
    tokens = word_tokenize(text)
    if 'not' in tokens: tokens.remove('not')  # Tokenize the text into words
    for word in tokens:
        # pos_tag = nltk.pos_tag([word])[0][1][0].upper()  # Get the POS tag for the word
        # pos_tag = pos_tag if pos_tag in ['N', 'V', 'R', 'J'] else wordnet.NOUN  # Convert POS tag to WordNet format
        lemma = lemmatizer.lemmatize(word, pos='v')  # Lemmatize the word
        lemmatized_text.append(lemma)
    return ' '.join(lemmatized_text)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SVI\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SVI\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [42]:
df['text'].head(30).values

array(['great cooler excellent air flow price amazing unbelievablejust love',
       'best budget 2 fit cooler nice cooling',
       'quality good power air decent', 'bad product fan',
       'ok ok product',
       'cooler really fantastic provides good air flow highly recommended',
       'good product', 'nice', 'bad cooler', 'good',
       'beautiful product good material perfectly working', 'awesome',
       'wonderful product must buy',
       'nice air cooler smart cool breeze producer', 'awsm',
       'nice product', 'great cooler', 'nice product reasonable price',
       'like', 'goodd', 'good product kawaleti',
       'good cooler amazing beautiful designs affordable price',
       'using since 3months great experience',
       'good performance nice look',
       'product good strong thrust air flow must buy', 'bad quality',
       'soundless product low price company',
       'best poduct bought flifkart works superb like ac price also reasonable rs 8698',
       'cooler big

In [43]:
df['text'] = df['text'].apply(lemmatize_text)

In [44]:
df['text'].head(30).values

array(['great cooler excellent air flow price amaze unbelievablejust love',
       'best budget 2 fit cooler nice cool',
       'quality good power air decent', 'bad product fan',
       'ok ok product',
       'cooler really fantastic provide good air flow highly recommend',
       'good product', 'nice', 'bad cooler', 'good',
       'beautiful product good material perfectly work', 'awesome',
       'wonderful product must buy',
       'nice air cooler smart cool breeze producer', 'awsm',
       'nice product', 'great cooler', 'nice product reasonable price',
       'like', 'goodd', 'good product kawaleti',
       'good cooler amaze beautiful design affordable price',
       'use since 3months great experience', 'good performance nice look',
       'product good strong thrust air flow must buy', 'bad quality',
       'soundless product low price company',
       'best poduct buy flifkart work superb like ac price also reasonable rs 8698',
       'cooler big wide maharaja brand trust 

In [45]:
X = df['text']
y = df['label']

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [47]:
X = tfidf.fit_transform(X)

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [49]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.linear_model import LogisticRegression

In [50]:
# model_params = {
#     'svm': {
#         'model': SVC(gamma='auto'),
#         'params' : {
#             'C': [1,10,20],
#             'kernel': ['rbf','linear']
#         }  
#     },
#     'random_forest': {
#         'model': RandomForestClassifier(),
#         'params' : {
#             'n_estimators': [1,2,3,5,10,15,20]
#         }
#     },
#     'logistic_regression' : {
#         'model': LogisticRegression(solver='liblinear',multi_class='auto'),
#         'params': {
#             'C': [1,5,10,15,20,30,40,50,70,90,100]
#         }
#     },
#     'naive_bayes_gaussian': {
#         'model': GaussianNB(),
#         'params': {}
#     },
#     'naive_bayes_multinomial': {
#         'model': MultinomialNB(),
#         'params': {}
#     },
#     'decision_tree': {
#         'model': DecisionTreeClassifier(),
#         'params': {
#             'criterion': ['gini','entropy'],
            
#         }
#     }     
# }


In [51]:
from sklearn.model_selection import GridSearchCV

In [52]:
# scores=[]
# for model_name,mp in model_params.items():
#     clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
#     clf.fit(X_train,y_train)
#     scores.append({
#         'model':model_name,
#         'best_score':clf.best_score_,
#         'best_params':clf.best_params_
#     })
# df = pd.DataFrame(scores,columns=['model','best_score','best_params'])

In [53]:
lr = LogisticRegression(solver='liblinear',multi_class='auto',C=1)

In [54]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [56]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8083445066645635
[[ 4911  1610   135]
 [  537 25400   256]
 [  666  4086   436]]


In [58]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)

MultinomialNB()

In [59]:
y_pred1 = mnb.predict(X_test)

In [60]:
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))

0.7746404816363015
[[ 3568  3075    13]
 [  279 25883    31]
 [  388  4786    14]]


In [66]:
clf = DecisionTreeClassifier(criterion='entropy')

In [67]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [71]:
y_pred2 = clf.predict(X_test)

In [73]:
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))

0.7349948734127297
[[ 4481  1502   673]
 [ 1286 22527  2380]
 [  803  3436   949]]


In [74]:
clf = RandomForestClassifier(n_estimators=1)

In [75]:
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1)

In [76]:
y_pred3 = clf.predict(X_test)

In [77]:
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))

0.6875410784236401
[[ 3866  2076   714]
 [ 1998 21343  2852]
 [  806  3439   943]]


In [79]:
from sklearn.model_selection import GridSearchCV

# Define the grid of parameters to search
param_grid = {
    'C': [0.1, 1, 10, 100],  
    'penalty': ['l1', 'l2']
}

# Initialize Logistic Regression model
lr = LogisticRegression(solver='liblinear', multi_class='auto')

# Initialize GridSearchCV
clf = GridSearchCV(lr, param_grid, cv=5)

# Fit GridSearchCV to the training data
clf.fit(X_train, y_train)

# Get the best parameters found by GridSearchCV
best_params = clf.best_params_

# Create a new Logistic Regression model with the best parameters
best_lr = LogisticRegression(solver='liblinear', multi_class='auto', **best_params)

# Train the model with the best parameters on the entire training data
best_lr.fit(X_train, y_train)

# Make predictions on the test data
y_pred = best_lr.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8083445066645635
[[ 4911  1610   135]
 [  537 25400   256]
 [  666  4086   436]]
